NEWS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls")),
    path("blog/", include("blog_app.urls")),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspaper/models.py
from django.db import models


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # do not create table for this model


class Category(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(TimeStampModel):
    STATUS_CHOICES = [
        ("active", "Active"),
        ("inactive", "Inactive"),
    ]
    title = models.CharField(max_length=200)
    content = models.TextField()
    featured_image = models.ImageField(upload_to="post_images/%Y/%m/%d", blank=False)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    published_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="active")
    views_count = models.PositiveBigIntegerField(default=0)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Contact(TimeStampModel):
    message = models.TextField()
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Comment(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return f"{self.email} | {self.comment[:70]}"


class Newsletter(TimeStampModel):
    email = models.EmailField()


    def __str__(self):
        return f"{self.email}"

## 1 - 1 Relationship
# 1 user can have one 1 profile   => 1
# 1 profile is associated to one 1 user  => 1
# OneToOneField()


## 1 - M Relationship
# 1 user can post M post  => M
# 1 post is associated to only 1 user => 1
# In django use ForeignKey => many side

# 1 Post can contain M comment => M
# 1 Comment is associated to only 1 post = > 1

# 1 category can have M posts => M
# 1 post is associated to only 1 Category => 1

## M - M Relationship
# 1 student can learn from M teachers => M
# 1 teacher can teach M students => M
# ManyToManyField() => Any place

# 1 post can contain M tags => M
# 1 tag can be added to M posts => M

templates/aznews/main/detail/left/author.html
{% load static %}

<div class="blog-author">
  <div class="media align-items-center">
    <img src="{% static 'aznews/assets/img/author.png' %}"
         alt="{{ post.author.username }}">
    <div class="media-body">
      <a href="#">
        <h4>{{ post.author.get_full_name }}</h4>
      </a>
      <p>@ {{ post.author.username }}</p>
    </div>
  </div>
</div>

templates/aznews/main/detail/left/comment_form.html
<div class="comment-form">
  <h4>Leave a Reply</h4>
  <form class="form-contact comment_form"
        action="{% url 'comment' %}"
        id="commentForm"
        method="POST">
    {% csrf_token %}
    <input type="hidden" name="post" value="{{ post.id }}">
    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <textarea class="form-control w-100"
                    name="comment"
                    id="comment"
                    cols="30"
                    rows="9"
                    placeholder="Write Comment"></textarea>
          {{ form.comment.errors }}
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <input class="form-control"
                 name="name"
                 id="name"
                 type="text"
                 placeholder="Name">
          {{ form.name.errors }}

        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <input class="form-control"
                 name="email"
                 id="email"
                 type="email"
                 placeholder="Email">
          {{ form.email.errors }}
        </div>
      </div>
    </div>
    <div class="form-group">
      <button type="submit" class="button button-contactForm btn_1 boxed-btn">Send Message</button>
    </div>
  </form>
</div>

templates/aznews/main/detail/left/comment_list.html
{% load static %}
 
<div class="comments-area">
  <h4>{{ post.comment_set.count }} Comments</h4>
  {% for comment in post.comment_set.all %}
    <div class="comment-list">
      <div class="single-comment justify-content-between d-flex">
        <div class="user justify-content-between d-flex">
          <div class="thumb">
            <img src="{% static "aznews/assets/img/author.png" %}"
                 alt="{{ comment.name }}">
          </div>
          <div class="desc">
            <p class="comment">{{ comment.comment }}</p>
            <div class="d-flex justify-content-between">
              <div class="d-flex align-items-center">
                <h5>
                  <a href="#">{{ comment.name }}</a>
                </h5>
                <p class="date">{{ comment.created_at }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

templates/aznews/main/detail/left/post_detail.html
<div class="single-post">
  <div class="feature-img">
    <img class="img-fluid"
         src="{{ post.featured_image.url }}"
         alt="{{ post.title }}">
  </div>
  <div class="blog_details">
    <h2>{{ post.title }}</h2>
    <ul class="blog-info-link mt-3 mb-4">
      <li>
        <a href="#"><i class="fa fa-user"></i>{{ post.tag.all|join:", " }}</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-eye"></i>{{ post.views_count }} Views</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-comments"></i> 03 Comments</a>
      </li>
    </ul>
    <p>{{ post.content|linebreaksbr }}</p>
  </div>
</div>

templates/aznews/main/detail/left/post_nav.html
<div class="navigation-top">
  <div class="d-sm-flex justify-content-between text-center">
    <p class="like-info">
      <span class="align-middle"><i class="fa fa-heart"></i></span> Lily and 4
      people like this
    </p>
    <div class="col-sm-4 text-center my-2 my-sm-0">
      <!-- <p class="comment-count"><span class="align-middle"><i class="fa fa-comment"></i></span> 06 Comments</p> -->
    </div>
    <ul class="social-icons">
      <li>
        <a href="#"><i class="fab fa-facebook-f"></i></a>
      </li>
      <li>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </li>
      <li>
        <a href="#"><i class="fab fa-dribbble"></i></a>
      </li>
      <li>
        <a href="#"><i class="fab fa-behance"></i></a>
      </li>
    </ul>
  </div>
  <div class="navigation-area">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
        {% if previous_post %}
          <div class="thumb">
            <a href="{% url 'post-detail' previous_post.pk %}">
              <img class="img-fluid"
                   src="{{ previous_post.featured_image.url }}"
                   alt="{{ previous_post.title }}">
            </a>
          </div>
          <div class="arrow">
            <a href="{% url 'post-detail' previous_post.pk %}">
              <span class="lnr text-white ti-arrow-left"></span>
            </a>
          </div>
          <div class="detials">
            <p>Prev Post</p>
            <a href="{% url 'post-detail' previous_post.pk %}">
              <h4>{{ previous_post.title|truncatechars:24 }}</h4>
            </a>
          </div>
        {% endif %}

      </div>
      <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
        {% if next_post %}
          <div class="detials">
            <p>Next Post</p>
            <a href="{% url 'post-detail' next_post.pk %}">
              <h4>{{ next_post.title|truncatechars:24 }}</h4>
            </a>
          </div>
          <div class="arrow">
            <a href="{% url 'post-detail' next_post.pk %}">
              <span class="lnr text-white ti-arrow-right"></span>
            </a>
          </div>
          <div class="thumb">
            <a href="{% url 'post-detail' next_post.pk %}">
              <img class="img-fluid"
                   src="{{ next_post.featured_image.url }}"
                   alt="{{ next_post.title }}">
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>