NEWS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls")),
    path("blog/", include("blog_app.urls")),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspaper/models.py
from django.db import models


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # do not create table for this model


class Category(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(TimeStampModel):
    STATUS_CHOICES = [
        ("active", "Active"),
        ("inactive", "Inactive"),
    ]
    title = models.CharField(max_length=200)
    content = models.TextField()
    featured_image = models.ImageField(upload_to="post_images/%Y/%m/%d", blank=False)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    published_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="active")
    views_count = models.PositiveBigIntegerField(default=0)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Contact(TimeStampModel):
    message = models.TextField()
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Comment(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return f"{self.email} | {self.comment[:70]}"


class Newsletter(TimeStampModel):
    email = models.EmailField()


    def __str__(self):
        return f"{self.email}"

## 1 - 1 Relationship
# 1 user can have one 1 profile   => 1
# 1 profile is associated to one 1 user  => 1
# OneToOneField()


## 1 - M Relationship
# 1 user can post M post  => M
# 1 post is associated to only 1 user => 1
# In django use ForeignKey => many side

# 1 Post can contain M comment => M
# 1 Comment is associated to only 1 post = > 1

# 1 category can have M posts => M
# 1 post is associated to only 1 Category => 1

## M - M Relationship
# 1 student can learn from M teachers => M
# 1 teacher can teach M students => M
# ManyToManyField() => Any place

# 1 post can contain M tags => M
# 1 tag can be added to M posts => M

templates/aznews/main/list/right/categories.html
<aside class="single_sidebar_widget post_category_widget">
  <h4 class="widget_title">Category</h4>
  <ul class="list cat-list">
    {% for category in categories %}
      <li>
        <a href="#" class="d-flex">
          <p>{{ category.name|title }}</p>
          <p>({{ category.post_set.count }})</p>
        </a>
      </li>
    {% endfor %}
  </ul>
</aside>

templates/aznews/main/list/right/newsletter.html
<aside class="single_sidebar_widget newsletter_widget">
  <h4 class="widget_title">Newsletter</h4>
  <div id="newsletter_side_form_message"></div>

  <form action="" id="newsletter_side_form">
    {% csrf_token %}
    <div class="form-group">
      <input type="email"
             class="form-control"
             onfocus="this.placeholder = ''"
             onblur="this.placeholder = 'Enter email'"
             placeholder='Enter email'
             name="email"
             required>
    </div>
    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Subscribe</button>
  </form>
</aside>

templates/aznews/main/list/right/popular_posts.html
<aside class="single_sidebar_widget popular_post_widget">
  <h3 class="widget_title">Recent Post</h3>
  {% for recent_post in recent_posts %}
    <div class="media post_item">
      <img src="{{ recent_post.featured_image.url }}"
           alt="{{ recent_post.title }}"
           width="150px">
      <div class="media-body">
        <a href="single-blog.html">
          <h3>{{ recent_post.title|truncatechars:24 }}</h3>
        </a>
        <p>{{ recent_post.published_at|date:"F n, Y" }}</p>
      </div>
    </div>
  {% endfor %}
</aside>y

templates/aznews/main/list/right/search_form.html
<aside class="single_sidebar_widget search_widget">
  <form action="{% url 'post-search' %}" method="GET">
    <div class="form-group">
      <div class="input-group mb-3">
        <input type="text"
               class="form-control"
               placeholder='Search Keyword'
               onfocus="this.placeholder = ''"
               onblur="this.placeholder = 'Search Keyword'"
               name="query"
               value="{{ query }}">
        <div class="input-group-append">
          <button class="btns" type="button">
            <i class="ti-search"></i>
          </button>
        </div>
      </div>
    </div>
    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Search</button>
  </form>
</aside>

templates/aznews/main/list/right/tags.html
<aside class="single_sidebar_widget tag_cloud_widget">
  <h4 class="widget_title">Tag Clouds</h4>
  <ul class="list">
    {% for tag in tags %}
      <li>
        <a href="#">{{ tag.name }}</a>
      </li>
    {% endfor %}
  </ul>
</aside>