NEWS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls")),
    path("blog/", include("blog_app.urls")),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path

from blog_app import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path("post-detail/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("draft-list/", views.DraftListView.as_view(), name="draft-list"),
    path("draft-detail/<int:pk>/", views.DraftDetailView.as_view(), name="draft-detail"),
    path("draft-publish/<int:pk>/", views.DraftPublishView.as_view(), name="draft-publish"),
    path("post-delete/<int:pk>/", views.PostDeleteView.as_view(), name="post-delete"),
    path("post-create/", views.PostCreateView.as_view(), name="post-create"),
    path("post-update/<int:pk>/", views.PostUpdateView.as_view(), name="post-update"),
]

templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Personal Blog</title>
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap"
          rel="stylesheet">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
  </head>
  <body>
 
 
    <div class="page-header">

      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">logout</span>
        </a>

        <a href="{% url 'blog:post-create' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">add</span>
        </a>

        <a href="{% url 'blog:draft-list' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">draft</span>
        </a>
 
      {% else %}
        <a href="{% url 'login' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">login</span>
        </a>
 
      {% endif %}
 

 


      <h1>
        <a href="/">
          <img src="{% static 'blog/img/favicon.ico' %}"
               alt="Personal Blog"
               width="90px;">
          Personal Blog
        </a>
      </h1>
    </div>
    <div class="container content">
      {% block content %}
 
      {% endblock content %}
    </div>
    <script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

templates/blog/draft_detail.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      <div class="post">
        <div class="mt-2">
          <a href="{% url 'blog:draft-publish' post.pk %}" class="btn btn-success">Publish</a>
        </div>
        <h1>
          <a href="#">{{ post.title }}</a>
        </h1>
        <div class="mt-2 my-2">
          <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url 'blog:post-delete' post.pk %}" class="btn btn-danger">Delete</a>
        </div>
        <div class="date author">@{{ post.author.username }}</div>
        <p>{{ post.content }}</p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/blog/draft_list.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      {% for post in posts %}
        <div class="post">
          <h1>
            <a href="{% url 'blog:draft-detail' post.pk %}">{{ post.title }}</a>
          </h1>
          <div class="date author">@{{ post.author.username }}</div>
          <p>
            {{ post.content|truncatechars:200 }} <a href="{% url 'blog:draft-detail' post.pk %}">View more</a>
          </p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/blog/post_create.html
{% extends "blog/base.html" %}

{% block content %}
  <form action="" method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save</button>
  </form>
{% endblock content %}

templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      <div class="post">
        <div class="date">{{ post.published_at }}</div>
        <h1>
          <a href="#">{{ post.title }}</a>
        </h1>
        <div class="mt-2 my-2">
          <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url 'blog:post-delete' post.pk %}" class="btn btn-danger">Delete</a>
        </div>
        <div class="date author">@{{ post.author.username }}</div>
        <p>{{ post.content }}</p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      {% for post in posts %}
        <div class="post">
          <div class="date">{{ post.published_at }}</div>
          <h1>
            <a href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a>
          </h1>
          <div class="date author">@{{ post.author.username }}</div>
          <p>
            {{ post.content|truncatechars:200 }} <a href="{% url 'blog:post-detail' post.pk %}">View more</a>
          </p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}